[package]
name = "api-gateway"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
actix-web.workspace = true
actix-cors.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-actix-web.workspace = true
uuid.workspace = true
anyhow.workspace = true
thiserror.workspace = true
config.workspace = true
dotenvy.workspace = true
reqwest.workspace = true
jsonwebtoken.workspace = true

shared-infrastructure.workspace = true
shared-middleware.workspace = true
shared-errors.workspace = true
shared-telemetry.workspace = true

[lints]
workspace = true
