[alias]
lint = "clippy --all-targets --all-features --workspace -- -D warnings"
fmt = "fmt --all"
check-fmt = "fmt --all -- --check"
fix-lint = "clippy --all-targets --all-features --workspace --fix -- -D warnings"

[build]
rustflags = [
    "-Dwarnings",                   # Treat warnings as errors
    "-Wclippy::all",                # Enable all Clippy lints
    "-Wclippy::pedantic",           # Pedantic lints
    "-Aclippy::module_name_repetitions"     # Disable overly noisy lint
]
incremental = true
