apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: luminara-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: luminara
  
  source:
    repoURL: https://github.com/Vickouma77/luminara.git
    targetRevision: main
    path: k8s/overlays/staging
  
  destination:
    server: https://kubernetes.default.svc
    namespace: luminara-staging
  
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  revisionHistoryLimit: 20
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
